version: 0.0
os: linux

files:
  # S3에 저장한 파일들 중 destination(AWS EC2)으로 이동시킬 대상을 지정한다.
  # / 이라고 지정하면 S3에 저장한 전체 파일을 뜻한다.
  - source: /
    # EC2의 어떤 경로에 저장할 지 지정한다.
    destination: /home/ubuntu/shared-review

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu

# permissions: 파일 및 디렉토리의 소유자와 그룹을 지정합니다.
#object: 권한을 설정할 파일 또는 디렉토리의 경로를 지정. /는 모든 파일을 의미.
#owner: 파일의 소유자를 지정. 여기서는 ubuntu로 설정되어 있.
#group: 파일의 그룹을 지정. 여기서는 ubuntu로 설정
#hooks: 배포 과정 중 특정 시점에 실행할 스크립트를 지정
#ApplicationStart: 애플리케이션 시작 시 실행할 스크립트를 지정함.
#location: 실행할 스크립트의 경로를 지정합니다. 여기서는 scripts/start-server.sh로 설정되어 있음.
#timeout: 스크립트 실행의 타임아웃 시간을 초 단위로 지정합니다. 여기서는 60초로 설정되어 있음.
#runas: 스크립트를 실행할 사용자를 지정합니다. 여기서는 ubuntu로 설정되어 있음