name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{secrets.APPLICATION_DEV}}" > ./sharedReview/src/main/resources/application-dev.yml

      - name: application-dev.yml  파일 내용 확인
        run: cat ./sharedReview/src/main/resources/application-dev.yml

      - name: 권한 부여
        run: chmod +x ./sharedReview/gradlew

      - name: 빌드하기
        run: |
          cd sharedReview
          ./gradlew clean build        
