name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
#      - name: application.yml 파일 만들기
#        run: printf "%s" "${{secrets.APPLICATION_DEV}}" | base64 --decode > ./sharedReview/src/main/resources/application-dev.yml

      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.11
        with:
          character set server: 'utf8'
          mysql database: 'shared_review'
          mysql user: 'sr'
          mysql password: '1234'

      - name: 권한 부여
        run: chmod +x ./sharedReview/gradlew

      - name: 빌드하기
        run: |
          cd sharedReview
          ./gradlew clean build        
