spring:
#  config:
#    import: classpath:application-secret.yml


  datasource:
    url: jdbc:mariadb://121.166.3.16/shared_review
#    url: jdbc:mariadb://127.0.0.1:3307/shared_review
    username: sr #sr
    password: 1234 #1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#        이메일 인증 기능 구현하기 위한 데이터들
  mail:
    host: smtp.gmail.com # smtp.naver.com
    port: 587 #  구글은 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  auth-code-expiration-millis: 9000000

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate:
      type:
        descriptor:
          sql: trace
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
    session:
      tracking-modes: cookie
file:
  path: C:/upload/
  url: http://localhost:8080/file/
  temp: C:/upload/temp/
  tempUrl: http://localhost:8080/file/temp/
  maximum: 10000000

jwt:
  secretKey: dkiizckkK!@#Zddkzdiz!@KFADFZCXVasdsadvCXVASDQWDDASDZXCsDFDSdx1231412
  refreshKey: dkiizckkK!@#Zddkzdiz!@KFADFZCXVasdsadvCXVASDQWDDASDZXCsDFDSdx1231412
